spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/viprko/the-garden-foretells-config
          default-label: main
          skipSslValidation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888
