spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/projects/config-servers/pet.the-garden-foretells-config
          default-label: main
          skipSslValidation: true

server:
  port: 8888
